server:
        port: 9090
spring:
        application:
               name: API-Gateway              
        cloud: 
          gateway:
            routes:
            - id: Admin-service
              uri: http://localhost:8081/
              predicates:
               - Path=/admin/**
              filters:
              - StripPrefix=1
            - id: Doctor-service
              uri: http://localhost:8082/
              predicates:
               - Path=/doctor/**
              filters:
              - StripPrefix=1
            - id: Order-Inventory-service
              uri: http://localhost:8083/
              predicates:
              - Path=/order/**  
              filters:
              - StripPrefix=1
            - id: Drug-Inventory-Service
              uri: http://localhost:8085/
              predicates:
              - Path=/drug/**  
              filters:
              - StripPrefix=1
            - id: Supplier-Inventory-service
              uri: http://localhost:8085/
              predicates:
              - Path=/supplier/**  
              filters:
              - StripPrefix=1 
            
  
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true






            
     
            
           
          


              




