
server:
     port: 8081
spring:
     application:
            name: Admin-Service

#for swagger after linking if eror come
     mvc:
        pathmatch:
                matching-strategy: ant-path-matcher

#To link Mongodb with spring boot
     data: 
         mongodb: 
                uri: mongodb+srv://Samuel7531:Alpha7531@cluster0.8krkp.mongodb.net/test

#registering to eureka
eureka:
     client:
         register-with-eureka: true
         fetch-registry: true

