server:
        port: 9090
spring:
        application:
               name: Cloud-gateway        
        cloud: 
          gateway:
            routes:
            - id: Admin-Service
              uri: http://localhost:8081/
              predicates:
              - Path=/admin/**
              filters:
              - StripPrefix=1
            - id: Doctor-Service
              uri: http://localhost:8082/
              predicates:
              - Path=/doctor/**
              filters:
              - StripPrefix=1
            - id: Drug-Inventory-Service
              uri: http://localhost:8084/
              predicates:
              - Path=/drug/**  
              filters:
              - StripPrefix=1
            - id: Supplier-inventory-Service
              uri: http://localhost:8085/
              predicates:
              - Path=/supplier/**
              filters:
              - StripPrefix=1 
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true






            
     
            
           
          


              




